# This is a test Ansible playbook to setup trojanwall application in Kubernetes Cluster.
# author: Arjun B Nair


---

- hosts: kubemaster
  become: yes
  vars:
    packages: ['docker','git']
  tasks:
  - name: Installing Required Packages
    apt:
      name={{packages}}
      state=latest
  - debug:
      msg:
      - "Packages installed: {{packages}}."

  - name: Pulling from Trojanwall Git Repository
    shell: |
      chmod +x /etc
      cd /etc ; mkdir trojanwall-kube
      cd /etc/trojanwall-kube
      git init
      git remote add origin https://gitlab.com/arbnair97/trojanwall-kuberentes.git
      git checkout -b master
      git pull https://gitlab.com/arbnair97/trojanwall-kuberentes.git master
  - debug:
      msg:
      - "Trojanwall Repository Pulled from Gitlab."
      - "Kubernetes Cluster ready for configuration."
    
  - name: Trojanwall App deployment
    shell: |
      cd /etc/trojanwall-kube
      kubectl create -f namespace.yml 
      cd Postgres
      kubectl create -f pg_secrets.yml
      kubectl create -f pg_pv.yml
      kubectl create -f pg_deploy.yml
      cd ../Django
      kubectl create -f django_secrets.yml
      sleep 1m
      kubectl create -f django_deploy.yml
      kubectl create -f django_job.yml
      
  - debug:
      msg:
      - "Trojanwall successfully deployed to Kuberentes Cluster."

  - name: Kubernetes Cluster pods check
    shell: |
      kubectl get pods -n trojanwall
      kubectl get svc -n trojanwall
