---

- hosts: winserver
  gather_facts: no
  
  tasks:
  - name: Ping test from Ansible Engine to Windows Host
    win_ping:
  - debug:
      msg:
      - "Connection from Ansible Engine to Windows Host Machines Established."
      
  - name: Start Windows Module Installer Service
    win_service:
      name: TrustedInstaller
      start_mode: manual
      state: started
    
  - debug:
      msg:
      - "Successfully started Windows Module Installer Service."
      
  - name: Start Windows Update Service
    win_service:
      name: wuauserv
      start_mode: manual
      state: started
    
  - debug:
      msg:
      - "Successfully started Windows Update Service."
      
  - name: Search for new available updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - DefinitionUpdates
      - UpdateRollups
      - Updates
      state: searched
      category_names: "{{ win_updates_categories }}"
      register: update_count
      ignore_errors: yes
      log_path: c:\ansible_wu.txt
      
  - name: Install all critical and security updates in Windows Host Machines
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - DefinitionUpdates
      - UpdateRollups
      - Updates
      category_names: "{{ win_updates_categories }}"
      state: installed
    register: update_result
 
  - name: reboot host if required
    win_reboot:
    when: update_result.reboot_required
      
      
