---

- hosts: winserver
  gather_facts: no
  vars:
    win_updates_categories:
      - SecurityUpdates
      - CriticalUpdates
      - DefinitionUpdates
      - Updates
  
  tasks:
  - name: Ping test from Ansible Engine to Windows Host
    win_ping:
  - debug:
      msg:
      - "Connection from Ansible Engine to Windows Host Machines Established."
      
  - name: Start Windows Module Installer Service
    win_service:
      name: TrustedInstaller
      start_mode: manual
      state: started
    
  - debug:
      msg:
      - "Successfully started Windows Module Installer Service."
      
  - name: Start Windows Update Service
    win_service:
      name: wuauserv
      start_mode: manual
      state: started
    
  - debug:
      msg:
      - "Successfully started Windows Update Service."
      
  - name: Search for new available updates
    win_updates:
      category_names: "{{ win_updates_categories }}"
      #whitelist:
      #- KB2267602
      #- KB4586839
      state: searched
      register: update_count
      ignore_errors: yes
      log_path: c:\ansible_wu.txt
      
  - name: Install all critical and security updates in Windows Host Machines
    win_updates:
      category_names: "{{ win_updates_categories }}"
      #whitelist:
      #- KB2267602
      #- KB4586839
      state: installed
    register: update_result
  
 
  - name: Stop and Disable Windows Module Installer Service after Patching.
    win_service:
      name: TrustedInstaller
      start_mode: disabled
      state: stopped
  - debug:
      msg:
      - "Successfully stopped and disabled Windows Module Installer Service."
      
      
      
  - name: Stop and Disable Windows Update Service
    win_service:
      name: wuauserv
      start_mode: disabled
      state: stopped
  - debug:
      msg:
      - "Successfully stopped and disabled Windows Update Service."
      
      
      
  - name: Reboot Windows Host if required.
    win_reboot:
    when: update_result.reboot_required
      
      
